# numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

In [3]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [7]:
a = a.reshape(3,3)

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(a)

numpy.ndarray

In [10]:
a + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
a.shape

(3, 3)

In [12]:
a.size

9

In [13]:
a.ndim

2

In [14]:
a.dtype

dtype('int64')

In [15]:
a.itemsize

8

In [16]:
a = np.array([[1,2,3], [4,5,6]], dtype='int64')
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a.T   # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
a.flatten()
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [19]:
a = np.zeros([3,3], dtype=np.int64)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a + b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full([3,3], 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
np.linspace(10,20,3)

array([10., 15., 20.])

In [24]:
np.logspace(10,20,3)

array([1.e+10, 1.e+15, 1.e+20])

In [25]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a.max()

np.int64(9)

In [27]:
a.max(axis=0)  # maximun in each Column

array([7, 8, 9])

In [28]:
a.max(axis=1)  # maximun in each Row

array([3, 6, 9])

In [29]:
a.sum()

np.int64(45)

In [30]:
a.sum(axis=0)  # sum in each Column

array([12, 15, 18])

In [31]:
a.sum(axis=1)  # sum in each Row

array([ 6, 15, 24])

In [32]:
a.cumsum()  # cumulative

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [33]:
a.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [34]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [36]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [37]:
print(a.dot(b))  # 1*4 + 2*5 + 3*6

32


In [38]:
a * b

array([ 4, 10, 18])

In [39]:
a = np.array([[1,4,2], [3,4,6], [0,-1,5]])
a

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [40]:
np.sort(a, axis=0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [41]:
np.sort(a, axis=1)   # default --> axis=1

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [42]:
np.sort(a, axis=None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [43]:
print(np.sqrt(4))

2.0


In [44]:
print(np.sin(np.pi/2))

1.0


In [45]:
a = np.array([1,2,3])

In [46]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [48]:
a = np.array([4,5,2,1,3,9])
a

array([4, 5, 2, 1, 3, 9])

In [49]:
print(a[1])
print(a[[1,2]])

5
[5 2]


In [50]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [52]:
for i in a.flatten():
    print(i)

1
2
3
4
5
6


In [53]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a.reshape(3,2)  # return a copy

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a.resize(3, 2)  # change the origin

In [56]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
np.resize(a, [2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.hstack([a, b])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.column_stack([a,b])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [65]:
r = np.array([1,2,3])
s = np.array([4,5,6])

In [66]:
np.hstack([r,s])

array([1, 2, 3, 4, 5, 6])

In [67]:
np.vstack([r,s])

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.column_stack([r,s])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a.fill(1)     # change the origin

In [71]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [72]:
a = np.array([1,2,3,4,5,6])

In [73]:
a

array([1, 2, 3, 4, 5, 6])

In [74]:
a2 = a.copy()

In [75]:
a2

array([1, 2, 3, 4, 5, 6])

In [76]:
a = np.where(a>3, a, 0)

In [77]:
a

array([0, 0, 0, 4, 5, 6])

In [78]:
a2

array([1, 2, 3, 4, 5, 6])

In [79]:
b = np.array([1,2,3,4,5])

In [80]:
b2 = b

In [81]:
b.fill(1)

In [82]:
b

array([1, 1, 1, 1, 1])

In [83]:
b2

array([1, 1, 1, 1, 1])

In [84]:
a = np.array([5,6,1,3,7,8,9,4,2,4])

In [85]:
print(np.mean(a))

4.9


In [86]:
print(np.std(a))

2.4677925358506134


In [87]:
print(a.mean())

4.9


In [88]:
print(a.std())

2.4677925358506134


In [89]:
print(np.argmin(a))

2


In [90]:
print(np.argmax(a))

6


In [91]:
a = np.array([1,2,3])

In [92]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [93]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.diag(a)

array([1, 5, 9])

In [96]:
a > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [97]:
a[a > 5]

array([6, 7, 8, 9])

In [98]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
print(a[0])

[1 2 3]


In [100]:
print(a[0][0])

1


In [101]:
a = np.array([4,5,6])

In [102]:
a

array([4, 5, 6])

In [103]:
a[1:]

array([5, 6])

In [104]:
a[:] = 2

In [105]:
a

array([2, 2, 2])

In [106]:
a[0] = 99

In [107]:
a

array([99,  2,  2])

In [108]:
a = [1,2,3]
b = [4,5,6]

In [109]:
a + b

[1, 2, 3, 4, 5, 6]

In [110]:
import time

In [111]:
time.time()

1742674439.312491

In [112]:
a = [1,2,3]
b = [4,5,6]

In [113]:
res = []
for i in range(len(a)):
    res.append(a[i] + b[i])
print(res)

[5, 7, 9]


In [114]:
c = np.array([1,2,3])
d = np.array([4,5,6])

In [115]:
c + d

array([5, 7, 9])

In [116]:
type(a)

list

In [117]:
type(c)

numpy.ndarray

In [118]:
import time
import numpy as np
def nu():
    t1 = time.time()
    a = np.arange(1000000)
    b = np.arange(1000000)
    c = a + b
    t2 = time.time()
    print(t2 - t1)
nu()

0.021049976348876953


In [119]:
import time
import numpy as np
def py():
    t1 = time.time()
    c = range(1000000)
    d = range(1000000)
    e = []
    for i in range(len(c)):
        e.append(c[i] + d[i])
    t2 = time.time()
    print(t2 - t1)
py()

0.5525665283203125


# numpy random

In [120]:
import numpy as np

### create between [0,1)

In [121]:
print(np.random.rand())               # float
print(np.random.rand(5))              # numpy.ndarray
print(np.random.rand(3,3))            # numpy.ndarray

0.4319982620242404
[0.71994366 0.23677263 0.75543959 0.59827055 0.02094265]
[[0.66756758 0.12333022 0.82816932]
 [0.63266498 0.40782391 0.36952843]
 [0.73692593 0.16554559 0.88943869]]


### create sample   mean: 0   std: 1

In [122]:
print(np.random.randn())               # float
print(np.random.randn(5))              # numpy.ndarray
print(np.random.randn(3,3))            # numpy.ndarray

-0.8788900973284512
[-0.31738978  0.82860969  2.34950818  0.53123701 -1.25522383]
[[-0.24538958 -1.6325537   0.44759907]
 [ 0.64656952  0.97003565  0.50764267]
 [-1.11255323 -0.71368107  0.55674392]]


### create between [0,1)

In [123]:
print(np.random.random())             # float
print(np.random.random(5))            # numpy.ndarray
print(np.random.random([3,3]))        # numpy.ndarray

0.293264089383504
[0.25159    0.99465444 0.67433425 0.35328299 0.95919577]
[[0.81364272 0.78481079 0.32046827]
 [0.2241887  0.37988658 0.25982006]
 [0.76641305 0.66325929 0.58654919]]


### create normal sample

In [124]:
print(np.random.normal(65, 3))           # float
print(np.random.normal(65, 3, 5))        # numpy.ndarray
print(np.random.normal(65, 3, [3,3]))    # numpy.ndarray

60.69198667642427
[70.20455498 66.52078038 63.81871932 66.10889321 62.5046141 ]
[[72.47502575 61.11643191 66.62170172]
 [64.87121714 64.31611821 66.25120022]
 [64.7962027  65.37773247 62.65991023]]


### create random integer between [low, high)

In [125]:
print(np.random.randint(0,10))       # int
print(np.random.randint(0,10,5))       # numpy.ndarray
print(np.random.randint(0,10,[3,3]))       # numpy.ndarray

7
[7 1 9 9 2]
[[4 1 5]
 [6 2 6]
 [4 0 7]]


# etc

In [126]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [127]:
b = np.arange(15).reshape((3,5))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [128]:
np.random.shuffle(b)  # shuffle the rows and do not return
b

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [129]:
c = np.array([ 0,  1,  2,  3,  4])
np.random.choice(c)      # input must be 1D

np.int64(1)

In [130]:
a = np.arange(28)
a.reshape((-1, 7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])